#!/usr/bin/env bash
# Print the author UUID from one of YOUR existing reMarkable notebooks.
#
# Background: every page in a reMarkable notebook is tagged with a UUID that
# identifies the author (i.e. you, on a given device). Notebooks you created
# on your own tablet carry your account's author UUID; notebooks generated by
# this container ship with a fresh random UUID by default.
#
# If you want your auto-generated daily journals to be tagged as authored by
# you (matching the rest of your library), use this script to discover your
# UUID, then set AUTHOR_UUID in docker-compose.yml.
#
# Usage (inside the container):
#   /app/scripts/extract-author-uuid.sh "/path/to/your/notebook"
#
# Usage (from the host):
#   docker exec remarkable-daily-journal /app/scripts/extract-author-uuid.sh \
#       "/Quick sheets/Notebook 2"
#
# Pick any notebook YOU created on your tablet. Imported PDFs and Methods
# notebooks may not have a useful author UUID.
set -euo pipefail

NOTEBOOK_PATH="${1:-}"
if [ -z "$NOTEBOOK_PATH" ]; then
  cat >&2 <<EOF
Usage: $0 "<cloud path to a notebook you created>"

Examples:
  $0 "/Notebook 2"
  $0 "/Quick sheets/Daily plan"

Pick a notebook you HAND-CREATED on your reMarkable tablet (not an imported
PDF, not a Methods notebook). The script downloads it via rmapi, reads the
author UUID out of its .content metadata, and prints it.

Then add it to docker-compose.yml as:
  - AUTHOR_UUID=<the printed value>
EOF
  exit 64
fi

for dep in rmapi jq unzip; do
  command -v "$dep" >/dev/null 2>&1 || { echo "ERROR: '$dep' not found" >&2; exit 1; }
done

WORK="$(mktemp -d)"
trap '/bin/rm -rf "$WORK"' EXIT

if ! ( cd "$WORK" && rmapi get "$NOTEBOOK_PATH" >/dev/null 2>&1 ); then
  echo "ERROR: rmapi get '$NOTEBOOK_PATH' failed. Check the path with 'rmapi ls'." >&2
  exit 1
fi

BUNDLE="$(find "$WORK" -maxdepth 1 -name '*.rmdoc' -o -name '*.zip' | head -1)"
[ -n "$BUNDLE" ] || { echo "ERROR: rmapi downloaded nothing for '$NOTEBOOK_PATH'." >&2; exit 1; }

unzip -oq "$BUNDLE" -d "$WORK/unpacked"

UUID="$(jq -r '.cPages.uuids[0].first // empty' "$WORK"/unpacked/*.content 2>/dev/null | head -1)"
if [ -z "$UUID" ] || [ "$UUID" = "null" ]; then
  echo "ERROR: notebook has no cPages.uuids[0].first (likely an imported PDF or" >&2
  echo "       Methods notebook). Try a notebook you created by hand on the device." >&2
  exit 1
fi

echo "$UUID"
